In [1]:
import torch

## Introduction to Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [14]:
MATRIX = torch.tensor([[7, 8],
             [9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]]
                     )

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> repeat`

In [35]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6512, 0.5977, 0.0407, 0.2668],
        [0.8115, 0.6612, 0.6489, 0.3218],
        [0.7748, 0.0686, 0.3602, 0.3010]])

In [42]:
rand_img_size_tensor = torch.rand(224, 224, 3) # height, width, color channels
rand_img_size_tensor.ndim

3

### Zeroes and Ones

In [43]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
one = torch.ones(2, 3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [48]:
zero.dtype

torch.float32

## Ranges

In [58]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [64]:
float_tensor = torch.tensor([3., 6, 9])
float_tensor.dtype

torch.float32

In [65]:
float_16_tensor = float_tensor.type(torch.float16)

In [70]:
float_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors

In [76]:
# addition
torch.tensor([1, 2, 3]) + 10

tensor([11, 12, 13])

In [77]:
# subtraction
torch.tensor([1, 2, 3]) - 10

tensor([-9, -8, -7])

In [80]:
# multiplication
torch.tensor([1, 2, 3]) * 10

tensor([10, 20, 30])

In [79]:
# division
torch.tensor([1, 2, 3]) / 10

tensor([0.1000, 0.2000, 0.3000])

## Matrix Multiplication

In [87]:
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
# Element Wise
mat1 * mat2

tensor([[ 5, 12],
        [21, 32]])

In [88]:
# Matrix Multiplication
torch.matmul(mat1, mat2)

tensor([[19, 22],
        [43, 50]])