In [1]:
import torch

## Introduction to Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [14]:
MATRIX = torch.tensor([[7, 8],
             [9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]]
                     )

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> repeat`

In [35]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6512, 0.5977, 0.0407, 0.2668],
        [0.8115, 0.6612, 0.6489, 0.3218],
        [0.7748, 0.0686, 0.3602, 0.3010]])

In [42]:
rand_img_size_tensor = torch.rand(224, 224, 3) # height, width, color channels
rand_img_size_tensor.ndim

3

### Zeroes and Ones

In [43]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
one = torch.ones(2, 3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [48]:
zero.dtype

torch.float32

## Ranges

In [58]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [64]:
float_tensor = torch.tensor([3., 6, 9])
float_tensor.dtype

torch.float32

In [65]:
float_16_tensor = float_tensor.type(torch.float16)

In [70]:
float_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors

In [76]:
# addition
torch.tensor([1, 2, 3]) + 10

tensor([11, 12, 13])

In [77]:
# subtraction
torch.tensor([1, 2, 3]) - 10

tensor([-9, -8, -7])

In [80]:
# multiplication
torch.tensor([1, 2, 3]) * 10

tensor([10, 20, 30])

In [79]:
# division
torch.tensor([1, 2, 3]) / 10

tensor([0.1000, 0.2000, 0.3000])

## Matrix Multiplication

In [87]:
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
# Element Wise
mat1 * mat2

tensor([[ 5, 12],
        [21, 32]])

In [88]:
# Matrix Multiplication
torch.matmul(mat1, mat2)

tensor([[19, 22],
        [43, 50]])

## Aggregates


In [102]:
torch.rand(10).max()
torch.rand(10).std()
torch.rand(10).mean()
torch.rand(10).median()

tensor(0.5792)

In [107]:
torch.rand(10).argmax()
# returns the index

tensor(9)

In [104]:
torch.rand(10).argmin()

tensor(9)

For later `->` softmax activation function

### Reshaping Stacking Squeezing and Unsqueezing Tensors
* Reshaping - change shape of a tensor 
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions form a tensor
* Unsqueeze - add a `1` dimension to a target tensor

In [111]:
t1 = torch.arange(1., 10.)

In [116]:
# reshpe to add extra dimension
t1_reshape = t1.reshape(1, 9)

In [113]:
t1_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [117]:
t1.shape

torch.Size([9])

In [118]:
t1_reshape.shape

torch.Size([1, 9])

In [119]:
t1_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [124]:
t1[-2:]

tensor([8., 9.])

In [136]:
t2 = torch.arange(11., 20)

In [140]:
stack_1 = torch.stack((t1, t2))
stack_1

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [148]:
torch.squeeze(stack_1, dim=0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [153]:
stack_1.squeeze().shape

torch.Size([2, 9])

In [163]:
stack_1.squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [171]:
stack_1.unsqueeze(dim=2)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],

        [[11.],
         [12.],
         [13.],
         [14.],
         [15.],
         [16.],
         [17.],
         [18.],
         [19.]]])

## Numpy to PyTorch

In [177]:
import numpy as np
array = np.arange(1, 10)
# numpy array to pytorch tensor
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
# pytorch tensor to numpy array
tensor.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reproducibility

In [181]:
seed = 123
rand_a = torch.rand(3, 4)
rand_b = torch.rand(3, 4)
print(rand_a)
print(rand_b)

tensor([[0.0876, 0.1455, 0.6116, 0.7677],
        [0.5227, 0.1294, 0.8119, 0.4248],
        [0.1159, 0.5870, 0.2734, 0.7123]])
tensor([[0.8718, 0.6414, 0.7280, 0.9966],
        [0.1384, 0.7539, 0.3606, 0.8381],
        [0.8835, 0.6440, 0.6961, 0.2680]])


In [182]:
rand_a == rand_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [190]:
# setting random seed only works for one block of code
torch.manual_seed(seed)
torch.rand(3, 4)

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [192]:
# setting random seed only works for one block of code
torch.manual_seed(seed)
torch.rand(3, 4)

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

## Accessing GPU

In [202]:
# Running locally so no GPU available
torch.cuda.is_available()

False

In [195]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [199]:
tensor = torch.rand(10).to(device)

In [201]:
tensor.device

device(type='cpu')

In [207]:
# numpy array can't exist on gpu
# back to cpu
np_array = tensor.cpu().numpy()
np_array

array([0.7178835 , 0.7058374 , 0.91564953, 0.43398023, 0.07715076,
       0.35652554, 0.14786267, 0.53305334, 0.40664625, 0.23180753],
      dtype=float32)